require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'SocialApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # pod 'RNVectorIcons', path => '../node_modules/react-native-vector-icons'

  target 'SocialAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.

  # even_h파일이 없다는 build오류 나면 ({ 'Flipper' => '0.74.0' }) 추가 해줘야 함!!
  use_flipper!({ 'Flipper' => '0.74.0' })  
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
    end
  end
end


